language: node_js
node_js:
- 14
install:
- sudo apt-get update
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda env create -f environment.yml
- source activate vitessce-jupyter-dev
- pip install -e .
script:
- cd tests
- python -m unittest
- cd -
before_deploy:
- make html
- touch docs-dist/html/.nojekyll
deploy:
- provider: pages
  skip-cleanup: true
  github-token: $github_token
  local-dir: docs-dist/html
- provider: pypi
  skip-cleanup: true
  skip-existing: true
  username: "__token__"
  password:
    secure: Xing+GHVFzp9TnjLYUpb5rzl/0dSH4ZVFIUQXWVZEzeylOkh0z2/B6wKJ2uHH9CxXY+j3tP2oUYWIIR0LBb2CW8eWJCi3/enI+VmQKZ7i+5g35/VOb8iBvQZi5tW8iOPSj64wcSF5I334JHMfaiFTpgLKsz4vHttM9RPYtxTwgG18OIqau0R1ErXhm/CLKqhmAE4wyD06MU20vqxi3QC7OJ8FCYAfcA7XzI5jhSmz+khUqcIIJ/gI3TNPDNYxvpgjmOfPIette38jOZDwHO8IMf8J1kCF1jcihIlgJckalYMtA+31e1JY5sulG+ISGtuOHk4zA4KppERX0GBjoxXMXv4CQQyj7eMPFUtucu1FFoJHn0mjX9EUaTLidLbY9qKdGTobo7/csfvWqEVcwfGknojTCBF/FgFaJrYSbM1F3kbGqECW3PivTnhdfE9Jyu0L8X59bFImmmnxtL0lr2fIDX1e6VYmovh9Y1xT/28ZBvdzOD3LS8hBSlEThKsgwtnGrIR1cXSpu6S6mG5IIbQdG+TsvA9TRFFOTsidn0rjO2cTY4kwiQUO32LPx5QJwi11zx49zVOArNJygtu/nTrIS0UrXtMsueDPQr/rNDGd/2v8UrsdEvCJRl+mAQvy6tvO6EYH89A6cP7bFQZP2Dktap+PIrKHfO46JIYvH1FzYA=
- provider: npm
  skip-cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  src: ./js
