language: node_js
node_js:
  - 14
cache:
  directories:
    - js/node_modules
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Create conda environment
  - conda env create -f environment.yml
  # Activate the conda environment
  - source activate vitessce-jupyter-dev
  # Install the local vitessce package
  - pip install -e .
script:
  - cd test
  - bash download.sh
  - python -m unittest
before_deploy:
  - make html
  - touch docs-dist/html/.nojekyll
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $github_token
    local-dir: docs-dist/html
