name: vitessce-jupyter-dev
channels:
 - bioconda
 - conda-forge
dependencies:
 - python==3.8
 - numpy>=1.14.0
 - pandas>=1.1.2
 - anndata>=0.7.4
 - zarr>=2.5.0
 - numcodecs>=0.7.2
 - scipy>=1.0.0
 - dask>=2.30.0
 - pip
 - pip:
   - loompy>=3.0.6
   - sphinx
   - sphinx-rtd-theme